### ISSUE TITLE
Unable to convert pdf

### ISSUE THREAD

**Issue by sareporter** [freedomofpress/dangerzone#127]
I'm using Fedora 34. Attempting to convert a pdf results in a "Converting document to pixels" message, then after a few seconds, Dangerzone stops working with a "Failed :(" message. I also see a "Return Code 1" if that's relevant.

Thanks for any help you can offer ...

**Comment by apyrgio** [comment]
I believe we won't encounter this issue in the upcoming 0.8.0 release, since we no longer mount files to the Podman container, which was the underlying issue of our SELinux woes. See also https://github.com/freedomofpress/dangerzone/issues/880 for our work on making sure that Dangerzone works on systems with SELinux in enforcing mode.

If the upcoming 0.8.0 release does not fix this problem, feel free to reopen this issue.
