### ISSUE TITLE
Windows 10: Dangerzone 0.3.1 will not install

### ISSUE THREAD

**Issue by feathered-arch** [freedomofpress/dangerzone#150]
Installer states that a newer version is installed, and that in order to downgrade the newer version must first be uninstalled. 

I have never had Dangerzone installed on any of my devices (and I only learned about this software today).

**Comment by clock-cycle-horse** [comment]
RE: "Installer states that a newer version is installed, and that in order to downgrade the newer version must first be uninstalled.
I have never had Dangerzone installed on any of my devices"

I have exact same issue. The latest version and earlier version generate the same message quoted above. I too have never installed DangerZone

**Comment by Le1b1** [comment]
Maybe related to #153 ?

**Comment by deeplow** [comment]
@feathered-arch and @clock-cycle-horse can you confirm that you had onionshare installed before?

**Comment by feathered-arch** [comment]
> @feathered-arch and @clock-cycle-horse can you confirm that you had onionshare installed before?

Confirmed.

**Comment by deeplow** [comment]
Thanks @feathered-arch. Closing this as it is a duplicate of #153.
