### ISSUE TITLE
Bug: cannot install with Onionshare

### ISSUE THREAD

**Issue by Stunt8810** [freedomofpress/dangerzone#153]
Dangerzone version 0.3.1
Windows 11 22000.593
I can not install Dangerzone 0.3.1 after installing Onionshare 2.5. Error message: there already exist a higher version. It seems these 2 software share registry or something.

**Comment by micahflee** [comment]
Eek, that's not good. They're probably using the same package ID or something.

**Comment by mertdemir0** [comment]
I've same problem with version 0.3.1 also i tried older versions but still same error.
Windows 10 Pro version 21H2

**Comment by deeplow** [comment]
> Eek, that's not good. They're probably using the same package ID or something.

Precisely. The product upgrade seems to be the same on dangerzone and onionshare:
  - onionshare: https://github.com/onionshare/onionshare/blob/b7ec0cd9028efb74077d178f31ba7d3ba1d5041a/desktop/scripts/build-windows.py#L636
  - dangerzone: https://github.com/freedomofpress/dangerzone/blame/10dfc1441bcd066a7cc9803b4c368a12327f8590/install/windows/build-wxs.py#L218

According to the [windows installer docs](https://docs.microsoft.com/en-us/windows/win32/msi/using-an-upgradecode) (emphasis mine):

> Each stand-alone product should have its own UpgradeCode.

>  Product A and Product B were shipped with the same ProductLanguage, ProductVersion, and UpgradeCode. Product A and Product B have different ProductCodes. Because the products were assigned the same UpgradeCode, the Upgrade table cannot be authored to differentiate the older version of Product A from the older version of Product B. In this case, you will be unable to have an upgrade installation of Product A that ignores Product B. Because these were different products, **they should have each been assigned a different UpgradeCode**.

## Installing Onionshare after Dangerzone
Since onionshare has a bigger version number (2.5 vs 0.3.1) it will uninstall dangerzone. It does have a small conflict, though, where it won't run the installer until we close dangerzone:

![onioneshare-after-dz](https://user-images.githubusercontent.com/47065258/181238574-daf50cd4-ae74-46ba-8298-7da39f9a572c.PNG)


## Dangerzone after Onionshare
As reported originally by @w3AD4y-r5, it shows the following error and prevents the installation:

![dz-after-onionshare](https://user-images.githubusercontent.com/47065258/181238460-bf4f95c3-d78e-4a77-926a-48adf716ad88.PNG)

**Comment by deeplow** [comment]
Oddly enough I was unable to reproduce this in a newly installed windows 10 system.

I tried both combinations:
- installing dangerzone after onionshare
- installing onionshare after dangerzone

**Comment by deeplow** [comment]
Reviewing https://github.com/freedomofpress/dangerzone/pull/345#pullrequestreview-1306916150 actually lead me down a very similar path to solving this. So I took a bit of a deeper look at this one since it was so closely related. Here's what I found:

## User experience... if we simply [change the product code](https://github.com/freedomofpress/dangerzone/blame/10dfc1441bcd066a7cc9803b4c368a12327f8590/install/windows/build-wxs.py#L218)

**Scenario** The user has Dangerzone 0.4.0 installed and then 0.4.1 with a different product upgrade code. 

1. User launches the installer and all runs fine (apparently).
2. User launches Dangerzone in the start menu (there is only one Dangerzone app -- good) and it fails:

    ![image(13)](https://user-images.githubusercontent.com/47065258/220361165-76f9fbec-9164-47dd-8ac0-6c1b0c6d18fd.png)

3. To overcome this issue, the user has to uninstall the old version of the application (First Look Media one) from the control panel:
![image(14)](https://user-images.githubusercontent.com/47065258/220361535-58f04778-bb60-4f25-9d8e-f8bd0803479b.png)

    > **Note**: After uninstalling the old one (First Look Media, 0.4.0), the user won't find the Dangerzone icon on the start menu. 

4. In order to fix this, the user has to launch the installer for the new version and choose the repair option (default)

![image(15)](https://user-images.githubusercontent.com/47065258/220361976-b1ae475d-963c-4b3c-b592-e5c9ca2b3812.png)

After this it worked fine. But the upgrade process was far from smooth. We want to avoid this.

## Conclusion

We can't simply change the product code. There needs to be some more installer logic to uninstall the previous dangerzone version.

### What we'll probably need to do

1. Generate a new product code ([wix v3 docs](https://wixtoolset.org/docs/v3/howtos/general/generate_guids/))

2. Change the `build-wxs.py` (which generates the installer) to make it:
  1. [Find related products](https://wixtoolset.org/docs/v3/xsd/wix/findrelatedproducts/) (dangerzone) filter out versions higher than 0.4.0 (to exclude onionshare) 
  2. If found, [uninstall software the old dangerzone product code](https://stackoverflow.com/questions/31732240/how-do-you-uninstall-another-program-in-wix-installer)

### Further reading

- [Background on ProductUpgradeCode](https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming)
- [StackOverflow: uninstalling another program in wix installer](https://stackoverflow.com/questions/31732240/how-do-you-uninstall-another-program-in-wix-installer)
- [HowTo: Major upgrade (Wix v3 docs)](https://wixtoolset.org/docs/v3/howtos/updates/major_upgrade/)
- [Find related products (Wix v3 docs)](https://wixtoolset.org/docs/v3/xsd/wix/findrelatedproducts/)
- [Microsoft: removing existing products documentation](https://msdn.microsoft.com/library/aa371197.aspx)

**Comment by eloquence** [comment]
Thanks for the recap @deeplow . I would suggest we defer this for now from 0.4.1, unless we find ourselves with extra time on our hands because of final release infrastructure prep.

**Comment by deeplow** [comment]
Nice! That explains why it worked once and didn't work the other time for me. Maybe this is a smaller problem than we though (assuming most people download the 64 bit version -- which apparently I don't do from time to time).

**Comment by apyrgio** [comment]
Ok, let's wrap this up with a quick summary and a resolution:

Dangerzone erroneously had the same upgrade code as OnionShare (`12b9695c-965b-4be0-bc33-21274e809576`), when it was first conceived. This meant that you couldn't install Dangerzone alongside OnionShare.

A few months ago (October 2022), OnionShare [released v2.6](https://github.com/onionshare/onionshare/releases/tag/v2.6), with support for both 32-bit and 64-bit Windows binaries. This release kept the same upgrade code for the 32-bit binaries, but chose a different one for 64-bit binaries. The rationale is that the OnionShare project wants to phase out 32-bit binaries once Windows 10 becomes EOL (see https://github.com/onionshare/onionshare/issues/1557). This change meant that since October 2022, Dangerzone **can** be installed alongside OnionShare v2.6 (64-bit).

Given this update, we consider that changing the upgrade code of Dangerzone would be a difficult task with diminutive returns, since Dangerzone does not run in a 32-bit system. Instead, we suggest to any user that stumbles on this issue to use the 64-bit version of OnionShare. If there are any reasons why this is not possible in a 64-bit system, then feel free to reopen this issue and we will re-examine this decision.
