### ISSUE TITLE
Consider adding support for Ubuntu Focal

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#206]
Ubuntu 20.04 is still supported until April 2025, so we should consider adding it to the list of supported releases for users who haven't moved to Jammy yet.

**Comment by deeplow** [comment]
Apparently podman (on which the linux version depdends) is [not available](https://packages.ubuntu.com/focal/allpackages) on ubuntu focal and it requires [external repos](https://www.atlantic.net/dedicated-server-hosting/how-to-install-and-use-podman-on-ubuntu-20-04/) (linked [from the podman blog](https://podman.io/blogs/2021/06/16/install-podman-on-ubuntu.html)). 

And actually we do test podman on this exact ubuntu version (it's [where the CI tests the document conversion process](https://github.com/freedomofpress/dangerzone/blob/main/.circleci/config.yml#L130)).  And dangerzone had been available in the past for that ubuntu version.

@apyrgio will add the documentation to the installation instructions after successful testing & confirmation the packagecloud deb works for that version.

**Comment by deeplow** [comment]
It doesn't support python3.10 ([which we now need)](https://github.com/freedomofpress/dangerzone/pull/161) unless we add the deadsnakes as a dependency

**Comment by apyrgio** [comment]
Our Packagecloud repos for Ubuntu Focal do have a Dangerzone package, but the latest version is 0.2.1, which is the last version that supported Ubuntu Focal. See also https://github.com/freedomofpress/dangerzone/issues/160#issuecomment-1138970038. This means that we need to partially revert 229ebbda1499d29ea44099c28db25a921513cf9d, and create a 0.4 Ubuntu Focal package, besides adding Podman instructions.

Aside from that, I'd like to ask a quick question:

> It doesn't support python3.10 ([which we now need)](https://github.com/freedomofpress/dangerzone/pull/161) unless we add the deadsnakes as a dependency 

I believe this is no longer accurate, right? We had some minor Mypy issues in Python 3.9, but they are not important enough to switch to Python 3.10.

**Comment by apyrgio** [comment]
I can verify that we can install Dangerzone on Ubuntu Focal, if we install Podman first, with the instructions that we have in our CircleCI config. As for the .deb itself, I just downloaded it from Packagecloud, without adding the repo in the sources.

I haven't managed to test Dangerzone successfully though, because I encountered this issue:

```
/usr/lib/python3/dist-packages/click/core.py:940: Warning: Invoked legacy parameter callback "<function validate_input_filename at 0x7fc0e8cb61f0>".  The new signature for such callbacks starting with click 2.0 is (ctx, param, value).
  value, args = param.handle_parse_result(ctx, opts, args)
Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.3.2', 'console_scripts', 'dangerzone')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1476, in handle_parse_result
    value = invoke_param_callback(
  File "/usr/lib/python3/dist-packages/click/core.py", line 95, in invoke_param_callback
    return callback(ctx, value)
  File "/usr/lib/python3/dist-packages/dangerzone/errors.py", line 23, in wrapper
    return func(*args, **kwargs)
TypeError: validate_input_filename() missing 1 required positional argument: 'value'
```

Turns out that Click 7.x and below checked for the arguments that callbacks support, and if they were less than 3, it invoked the callback with less arguments (legacy mode):

https://github.com/pallets/click/blob/1784558ed7c75c65764d2a434bd9cbb206ca939d/src/click/core.py#L108-L112

In our case, our callback does support three arguments, but it's decorated with another function. This shouldn't be a problem because we use `functools.wraps(func)`, but turns out that it doesn't suffice, and the reported arguments for the function are 0. [Others have encountered](https://stackoverflow.com/questions/308999/what-does-functools-wraps-do) a similar problem, so we need to solve it similarly.
