### ISSUE TITLE
Defense in Depth - Generate a restricted seccomp profile

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#225]
Parent issue: https://github.com/freedomofpress/dangerzone/issues/221

Once an attacker has taken control of a process, and probably is root in the container (#224) they may attempt to escape the container by exploiting a vulnerability in the Linux kernel. The common interfaces that the Linux kernel provides are either special filesystems (#223) or system calls. In this issue, we will focus in the latter.

Containers run with a default seccomp filter that allows roughly 300 out of 435 system calls. Any vulnerability in the code path of these 300 system calls may be a way for an attacker to escape the container. So, it is very important to generate a seccomp profile for Dangerzone, that allowlists the system calls that are strictly necessary.

Further reading:
* https://podman.io/blogs/2019/10/15/generate-seccomp-profiles.html
* https://github.com/blacktop/seccomp-gen
* https://github.com/freedomofpress/dangerzone/issues/52 - seccomp mentioned but not implemented

**Comment by deeplow** [comment]
I am trying to find a reliable way to detect when the container failed due to a seccomp policy violation. To test this, I have a container calling `nc -l 8000`, which will call the `listen` system call. However, `nc` exits with `1` and not the seccomp default error that we set `222`.

We can see why this happens by doing `strace` on the process:

```
bind(3, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(3, 1)                            = -1 (errno 222)
writev(2, [{iov_base="nc: ", iov_len=4}, {iov_base=NULL, iov_len=0}], 2nc: ) = 4
writev(2, [{iov_base="listen", iov_len=6}, {iov_base=NULL, iov_len=0}], 2listen) = 6
writev(2, [{iov_base="", iov_len=0}, {iov_base=": ", iov_len=2}], 2: ) = 2
writev(2, [{iov_base="", iov_len=0}, {iov_base="No error information", iov_len=20}], 2No error information) = 20
writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2
) = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

The error number is received upon the syscall. Then program then deals with this however it wants. And it is unlikely that they way they want is to report the syscall error back to the calling program.

**Comment by apyrgio** [comment]
We can close this issue along with the gVisor integration, since the seccomp filter that gVisor provides is the strictest possible.
