### ISSUE TITLE
Support parallel conversions

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#257]
Parallel conversion is currently implemented [for the CLI](https://github.com/freedomofpress/dangerzone/blob/aba699/dangerzone/logic.py#L64) and [the graphical](https://github.com/freedomofpress/dangerzone/blob/aba699a2388f83e13723b55a1dbe18fb385842ef/dangerzone/gui/main_window.py#L592) versions of Dangerzone.

However, it increased increased the likelihood of timeout. We should figure out a better strategy to handle timeouts and only then allow parallel document conversions.

**Comment by Kol9yN** [comment]
here would be a good option for set how many cpu cores and memory program will consume

**Comment by apyrgio** [comment]
That would be a nice knob for advanced users.

Quick note on the status of this feature: parallel conversions can be tricky in case of OCR, since it can use up all of the host's CPU. Ideally, we need a processor pool that will be used both for the doc-to-pixel stage, and the pixel-to-doc stage, while taking into account that these jobs are dissimilar.

**Comment by Kol9yN** [comment]
what about use more containers then one for convert?
So DZ can convert more files (torrent like) at same time

**Comment by apyrgio** [comment]
Oh yeah, we already have a different container per document. But as I said, it's doable, just not in our top priorities. Especially if you use OCR, Dangerzone 0.11.0 will probably saturate half of your CPUs, so the parallel conversion may not be that much needed. Let us know once it's out!
