### ISSUE TITLE
Error in separating document into pages , timeout 120s

### ISSUE THREAD

**Issue by Bate5-m4wy** [freedomofpress/dangerzone#306]
I am new to coding and stuff so i dont know how can i increase the timeout delay of 'danger-zone' process as i saw another thread discussing this issue saying that a 1000 page pdf would need about 500 seconds or smth like that , so kindly can someone help me with it?
btw os: Win11

**Comment by apyrgio** [comment]
Right, the timeout problem has not been adequately addressed yet. Unfortunately, there is no CLI option that we can provide you to tweak it, so for now, you'd have to go in dev mode to change it. If you're up for it, I can guide you:

1. Download Dangerzone with [Git for Windows](https://git-scm.com/download/win).
1. Edit `dangerzone/container/dangerzone.py` with your editor, and bump this timeout to something higher:

   https://github.com/freedomofpress/dangerzone/blob/84b8212e5d85de7a1daf3d522d4f48402a1cbe00/container/dangerzone.py#L27
 
 1. Follow our [build instructions for Windows](https://github.com/freedomofpress/dangerzone/blob/main/BUILD.md#windows) and use `.\dev_scripts\dangerzone.bat` to run the edited Dangerzone app locally.
 
 Alternatively, you'd have to wait for the 0.4.1 release, where we address this problem. It's expected to be out in early February.

**Comment by apyrgio** [comment]
A bit more context for others that may encounter this problem:
 
### What is the underlying problem?

We are making a conversion from a single PDF to a PDF per page using a constant timeout for the whole process (120s). The reason we do so is because we don't know the number of pages at that point (see also https://github.com/freedomofpress/dangerzone/issues/70).

### How can we fix this problem?

We have a PR that replaces `pdftk` in favor of `pdftoppm`, and will add a timeout that is proportional to the number of pages (see https://github.com/freedomofpress/dangerzone/pull/305).

**Comment by Bate5-m4wy** [comment]
sorry for late replying , got busy
thank you so much i will try and tell u the result.
