### ISSUE TITLE
`pdfunite` times out on M1 Pro

### ISSUE THREAD

**Issue by HaydenSD** [freedomofpress/dangerzone#314]
I tried to use Dangerzone to convert a 800 page document to a PDF. Everything went fine up until the software tried to merge the PDF: it converts it to pixels and the pixels to PDF, but fails at merging the PDF. The error message I get is this: "error merging pages into document, pdfunite timed out after 120 seconds". I am running the latest ARM image of Docker and the latest version of Dangerzone. Converting a three page document works just fine. Any suggestions?

**Comment by deeplow** [comment]
Sorry about that. We're working on improving the conversion speeds for M1 Macs. In the next release (within ~2 weeks) it should be faster since we'll be able to build directly for the processor architecture of M1 macs.  So waiting until the new release will fix the problem. In the meantime, if you have an older mac (but still supported with security updates) running an intel processor, it should be able to handle it.

In the release you're testing you're basically running a version for the old (intel) processors which takes extra time to convert them to the new ones. And this is probably why it's timing out.

**Comment by deeplow** [comment]
In any case @apyrgio we should should make the `pdfunite` timeout proportional to the number of pages. There's no reason for this and other conversion steps to be a fixed time.
