### ISSUE TITLE
Notice when installing from packages.freedom.press

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#394]
Running `sudo apt update` on Ubuntu 20.04 currently displays the following notice with our recommended packaging configuration:

```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.freedom.press/apt-tools-prod focal InRelease' doesn't support architecture 'i386'
```

**Comment by eloquence** [comment]
I saw this on my system because I had the `i386` architecture enabled for some legacy packages. After removing the architecture (which is not enabled by default), the notice disappears.

Open questions for me:
- Should we test on the `i386` architecture and explicitly enable it for our packages if they work on that architecture? Given the legacy nature of this architecture, I think "no" may be a perfectly reasonable answer there.
- If we don't enable it, should we do anything else to silence this notice for users who have it enabled?

**Comment by apyrgio** [comment]
Thanks for the input @legoktm. You're right, the container is 64-bit, so it wouldn't work on an i386 system. As for arm64 Linux systems, users _can_ build Dangerzone for them (we already do so for MacOS), but that would be a bespoke solution, not something we support.
 
For this reason, we already specify that this package is available only on `amd64` architectures: https://github.com/freedomofpress/apt-tools-prod/blob/main/repo/conf/distributions. So, if having an empty `arm64` / `i386` Release file is the way to go, we can move forward with that. I'd like to see if this is something that `reprepro` can natively support, so that we don't delete this file by mistake when rebuilding the repo, but that would be a low priority task.

**Comment by legoktm** [comment]
> For this reason, we already specify that this package is available only on `amd64` architectures: https://github.com/freedomofpress/apt-tools-prod/blob/main/repo/conf/distributions.

That is the architectures we provide the repository for, but the package itself is marked as being compatible with all architectures:
```
# apt-cache show ./dangerzone_0.4.1-1_all.deb       
Package: dangerzone
Version: 0.4.1-1
Architecture: all
...
```

(also the "all" in the filename gives it away...)

Presumably there's a setting for stdeb to set the package to `Architecture: amd64`...will look.

**Comment by legoktm** [comment]
Nope, it's hardcoded to check if there are extension modules, and if so, set `Architecture: any` (which would be fine here, it just means to use whatever architecture it was built on): https://github.com/astraw/stdeb/blob/3e6522cefa240be365ebdc0dc0c7923ba7118999/stdeb/util.py#L882

Maybe if we end up doing something like https://github.com/freedomofpress/dangerzone/issues/323#issuecomment-1485548943 we can sed the correct value into place?

**Comment by apyrgio** [comment]
A user [kindly pointed out](https://github.com/freedomofpress/dangerzone/issues/621) that we can restrict this repo to just amd64 packages, by adding `[arch=amd64]` to the Debian source line, i.e.:

```
deb [arch=amd64 signed-by=/etc/apt/keyrings/fpf-apt-tools-archive-keyring.gpg] https://packages.freedom.press/apt-tools-prod ${VERSION_CODENAME?} main
```

**Comment by apyrgio** [comment]
A potential issue with this fix though is that if a user is in a 32-bit system, they may erroneously install Dangerzone, which should not be available there. I think the fix that @legoktm suggested is better in the long run, but we haven't managed to work on it yet.
