### ISSUE TITLE
Qubes: Error handling

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#430]
We need to accommodate exceptions for all edge-cases in the client binary-protocol-parsing code. This was out of scope of the alpha stage (https://github.com/freedomofpress/dangerzone/issues/411).

Errors to check on server:
  - [x] **document wasn't immediately received**:
     probably the user exited dangerzone mid-conversion. Safely exit from dangerzone so that there isn't a dangling disposable qube
- [x] The number of received pages was (> MAX_PAGES)
    - **note:** this one is probably going to have to be done server-side. The (Qubes) client retrieves 2 bytes for pages. "Overflows" won't be detected.

Errors to check on the client:
- [x] The disposable qube could not start due to memory issues.
- [x] The disposable qube could not start because `dz-dvm` does not exist. (**update: done in https://github.com/freedomofpress/dangerzone/pull/564)
- [x] The width and the height of the pages are too large.
- [x] Page conversion timeout reached
- [x] Timed out receiving a page
- [x] Consume stderr ([source](https://github.com/freedomofpress/dangerzone/pull/437#discussion_r1236644777))
- [ ] Show helpful message if OCR step fails (e.g., unsupported language)
- [ ] <strike>  Stop disposable VMs when aborting conversions </strike> **update:** will be tackled separately since it also affects containers. Moved to https://github.com/freedomofpress/dangerzone/issues/563

Errors to check on the client:     

<strike>Also, we need to sanitize tracebacks and errors from the disposable qube, in a way that does not affect the user's terminal (e.g., remove control characters).</strike> **update**: this will be done in https://github.com/freedomofpress/dangerzone/pull/386

**Comment by deeplow** [comment]
I moved the "number of pages received" to be a server-side check. The client won't have a way of knowing this.

**Comment by apyrgio** [comment]
We were a bit overeager to close this issue, as there are still some error cases that are missing:

- [ ]  The disposable qube could not start because `dz-dvm` does not exist.
  * Currently, we return a wrong error message here, that the system was out of RAM, but this is not the case.
  * It's probably best to return a generic message here "Could not start disp qube `dz-dvm`. Consult your system logs". Qubes UI shows a notification with more context, after all.
- [ ]  Show helpful message if OCR step fails (e.g., unsupported language)
  - Admittedly, this error is unlikely to happen, because we now install every OCR language available.
  - I propose moving this to the stabilization effort.
- [ ] Stop disposable VMs when aborting conversions 
  * This is important and we need to fix it. I haven't managed to do so yet, sorry.
- [ ] Get notified about the command that failed while doing document conversion:
  * In practice, we have at most three commands that may run:
     1. [not required for PDFs] `libreoffice` , `gm`
     2. `pdfinfo`
     3. `pdftoppm`
    
     An error during `pdftoppm` is easy to detect, as we are in the middle of getting pages back. Errors between `pdfinfo` and `libreoffice` | `gm` are less easy to detect, so this still warrants a fix, although it's not very pressing. I'd move this to the stabilization effort as well.
