### ISSUE TITLE
Qubes: Install all other OCR languages

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#438]
The [Qubes integration PoC](https://github.com/freedomofpress/dangerzone/pull/437/files#diff-5329c15606ca4031db5859ba4eda36fc0c4e1f2c816a57b8ae30c0a33b0d28f0R49) only includes the English language. Since this is a packaging issue (#431) we haven't addressed it yet.

We can an approach similar to https://github.com/freedomofpress/dangerzone/pull/422, where we don't rely on OS-distributed languages.

**Comment by apyrgio** [comment]
Closing this issue, since we already have instructions for installing all the Tesseract OCR data: https://github.com/freedomofpress/dangerzone/blob/main/BUILD.md#in-the-fedora-37-dz-template

We should make sure that the final Dangerzone RPM / DEB packages for Qubes also install all the Tesseract files, but that's a discussion for another issue.
