### ISSUE TITLE
Support CJK characters

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#468]
We need to add CJK fonts for support [Chinese](https://en.wikipedia.org/wiki/Chinese_language), [Japanese](https://en.wikipedia.org/wiki/Japanese_language), and [Korean languages](https://en.wikipedia.org/wiki/Korean_language). We can use for example the package [font-noto-cjk-extra](https://pkgs.alpinelinux.org/package/edge/community/x86/font-noto-cjk-extra).

|**Before**|**After**|
|---|---|
| ![aaa](https://github.com/freedomofpress/dangerzone/assets/47065258/729e2deb-f5b2-48bf-a82d-32bc33d2b809) | ![aaabbb](https://github.com/freedomofpress/dangerzone/assets/47065258/573587bc-2400-48b4-8cc5-28e8eba2e211) |

**Comment by OctopusET** [comment]
https://github.com/freedomofpress/dangerzone/pull/460#issuecomment-1623445016
Like I commented here, there's some characters still not able to render. But only some very old articles would be the cases.

I think some day fonts should be added manually (and safely).

**Comment by OctopusET** [comment]
I have to test but [font-noto-cjk-extra](https://pkgs.alpinelinux.org/package/edge/community/x86/font-noto-cjk-extra) might be not necessary for just showing characters. Some fonts like 'bold' might be render different, but if you think it would increase image size a lot [font-noto-cjk](https://pkgs.alpinelinux.org/package/edge/community/x86/font-noto-cjk) would be enough

**Comment by OctopusET** [comment]
I tested with this [file](https://github.com/freedomofpress/dangerzone/files/11996543/TestKoreanFonts.odt).
This file contains the following fonts: "Noto Sans CJK KR *", "IBM Plex Sans KR *", "Noto Serif CJK KR *".


Original | font-noto-cjk | font-noto-cjk-extra
---      | ---           | ---
![Original image](https://github.com/freedomofpress/dangerzone/assets/18513799/3efae139-f820-4694-a858-313813fdeaf0) | ![font-noto-cjk image](https://github.com/freedomofpress/dangerzone/assets/18513799/b2003548-c227-42ee-afa4-59819be373a6)| ![font-noto-cjk-extra image](https://github.com/freedomofpress/dangerzone/assets/18513799/c59b68fd-b708-4c93-b859-c5719a87b54a)

I think font-noto-cjk would be sufficient. Although font-noto-cjk-extra can render much more fonts, but that's because those glyph (e.g. Noto Sans CJK Light) are also the noto fonts. For example, even IBM Plex Sans uses other glyph like 'IBM Plex Sans light' that Noto fonts can't render.

**Comment by deeplow** [comment]
Thanks for investigating. Looks like `font-noto-cjk` will have to cut it for now. `font-noto-cjk-extra` would add an extra 200MB of downloaded packages.
