### ISSUE TITLE
Use the fixed version on the Dockerfile

### ISSUE THREAD

**Issue by OctopusET** [freedomofpress/dangerzone#540]
Dangerzone uses Alpine image as base image.

Currently
```
FROM alpine:latest
```

Suggestion
```
FROM alpine:3.18
```
With fixed version, it would be easy to know which Alpine version the Dangerzone release is currently using.
Even Alpine's stable version changes occasionally, though there's a possibility of problems caused by version changes.

**Comment by apyrgio** [comment]
Personally, I'm in favor of using a mutable tag (`latest`) so that we can always stay up to date, even if a new stable version arrives. As for your counter arguments, they do make sense, but I'll try to explain why they don't apply to Dangerzone specifically:

* Associating an Alpine version with an Dangerzone release: We are uploading the `container.tar.gz` image that we use for a Dangerzone release (see our [Releases page](https://github.com/freedomofpress/dangerzone/releases)), which remains the same for the lifetime of a Dangerzone's release. So, if it's necessary to retrieve this information, it's pretty easy to find this out by loading this image.
* Software bugs due to newer images: Because we know that the container image is not updated, and because we perform extensive QA, we are pretty confident that we will catch Alpine Linux bugs during the QA process, before our users do.

So, the risks of staying on a less updated version outweigh the benefits, that's why I'd suggest following Alpine Linux's rolling model.

**Comment by OctopusET** [comment]
I didn't aware Dangerzone always using same `container.tar.gz`. 

And since this isn't edge image, so it's easy to track and know about alpine version and it doesn't change that often.

Agreed!
Although, I think it would be great if there's information about what alpine version is used for current release.

Thank you for great explanation.

If you think it can be closed. Please close the issue.

**Comment by apyrgio** [comment]
Thanks for the input. Closing this for now, but I'll keep it in mind in case we encounter a problem with this approach in the future.
