### ISSUE TITLE
Instruction to add repository in Ubuntu 23.10, missing arch parameter

### ISSUE THREAD

**Issue by clankgeek** [freedomofpress/dangerzone#621]
After apt update, the error message is displayed about i386

`N: Le fichier configuré « main/binary-i386/Packages » ne sera pas pris en compte car le dépôt « https://packages.freedom.press/apt-tools-prod mantic InRelease » ne prend pas en charge l'architecture « i386 »`

missing "arch=amd64"

```
source /etc/os-release
echo deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/fpf-apt-tools-archive-keyring.gpg] \
    https://packages.freedom.press/apt-tools-prod ${VERSION_CODENAME?} main \
    | sudo tee /etc/apt/sources.list.d/fpf-apt-tools.list

**Comment by apyrgio** [comment]
Hm, I think that adding `[arch=amd64]` will have adverse affects on an i386 system. The reason is that Dangerzone is not a 32-bit application, but a 64-bit one. With this line, you'd install a 64-bit application in your 32-bit system, which may create more issues.

See also the ongoing discussion here: https://github.com/freedomofpress/dangerzone/issues/394
