### ISSUE TITLE
PyMuPDF logging prints to stdout

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#700]
While converting a document on the [page streaming PR](https://github.com/freedomofpress/dangerzone/pull/627) I have just noticed the following:

![json](https://github.com/freedomofpress/dangerzone/assets/47065258/c9afda8c-f4c8-4f01-b3de-c2b9db8861a0)

[Here](https://github.com/pymupdf/PyMuPDF/blame/main/src/__init__.py#L9636)'s the line in question. It turns out that PyMuPDF's logging simply prints the error. Fortunately I haven't seen this in the pixels_to_PDF, but if it does happen it'll interfere with out page streaming since it assumes all stdout is pixel data.

**Comment by apyrgio** [comment]
Also, I've opened an issue in the PyMuPDF repo: https://github.com/pymupdf/PyMuPDF/issues/3135

**Comment by apyrgio** [comment]
Yeap, turns out that in 1.23.19, the `fitz_new` module became `fitz`, and `fitz` became `fitz_old`: ([changelog](https://github.com/pymupdf/PyMuPDF/blob/0a6f26db6fa1f230f44ab10d2a89515664927419/changes.txt#L144-L148), [rationale](https://github.com/pymupdf/PyMuPDF/discussions/2680)). Our use case is limited, and since our CI tests pass, it's probably best to follow suit.

**Comment by apyrgio** [comment]
There was another suggestion, of pinning PyMuPDF to 1.23.18 (now currently at 1.23.21), at least for this release. I looked into the PyMuPDF source, and I don't see any code changes in the `src_classic/` directory of PyMuPDF since 1.23.18, so we should be good.
