### ISSUE TITLE
No Package in F39 repo

### ISSUE THREAD

**Issue by larus-argentatus-hftp** [freedomofpress/dangerzone#702]
Hey, even though the issue (#680)  on Fedora 39 was closed I still cannot install Dangerzone on Fedora 39. I am using Fedora Silverblue.

**Steps**:
1. Add the `dangerzone.repo` file to `/etc/yum.repos.d/`;
2. Install by using the command `rpm-ostree install dangerzone`

When I looked into the [baseurl](https://packages.freedom.press/yum-tools-prod/dangerzone/) of `dangerzone.repo` I saw that the f39 directory only has the python-pyside6 files, not the dangerzone file.

**Comment by apyrgio** [comment]
We are actually about to release Dangerzone 0.6.0 in the coming days, and you will soon see a Dangerzone RPM in the Fedora 39 repo. The relevant issue (#680) has been closed because the necessary support has been added in the `main` branch. I'll add a comment in the issue to clarify this.

I'll now resolve this issue, but don't hesitate to comment if you have any other question.

**Comment by apyrgio** [comment]
Done, added some comments to clarify the situation:
* https://github.com/freedomofpress/dangerzone/issues/606#issuecomment-1934202891
* https://github.com/freedomofpress/dangerzone/pull/680#issuecomment-1934203858
