### ISSUE TITLE
Upgrading Dangerzone 0.5.0 to 0.6.0 on Fedora 38 may / will break the OCR component

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#737]
Upgrading Dangerzone 0.5.0 to 0.6.0 on Fedora 38 may / will break the OCR component. This can be easily fixed by appending the line

~~~
    export TESSDATA_PREFIX=/usr/share/tesseract/tessdata
~~~

to the file `.bash_profile` in the disposable template used for the Dangerzone dispVM.

_Originally posted by @GWeck in https://github.com/freedomofpress/dangerzone/issues/704#issuecomment-1974771165_

**Comment by apyrgio** [comment]
This issue has been fixed in our repo, but we also need to ship a new Dangerzone version for affected users. What we plan to do shortly is:

1. Use the latest commit in `main` (f75d471ec8ddb7d795c751a9dbf876ac7b175931 as of writing this).
2. Bump the release number from 1 to 2 in `install/linux/dangerzone.spec`:

   https://github.com/freedomofpress/dangerzone/blob/f75d471ec8ddb7d795c751a9dbf876ac7b175931/install/linux/dangerzone.spec#L36

3. Build a `dangerzone-qubes-0.6.0-2.fc38.x86_64.rpm` package. That is, build an RPM only for Fedora 38 and Qubes.
4. Publish this package in our `yum-tools-prod` repo, so that users who have installed `0.6.0-1` will get updated to `0.6.0-2`.

**Comment by apyrgio** [comment]
@GWeck we have a `0.6.0-2` release out for Fedora 38, that fixes this problem in particular. If you still have any issues with the new update, please let us know. Agains, thanks a lot for the bug report :slightly_smiling_face:
