### ISSUE TITLE
Dangerzone image doesn't build (errors during libmupdfcpp.so compilation)

### ISSUE THREAD

**Issue by stepnem** [freedomofpress/dangerzone#750]
As witnessed in the last two Tests runs ([last one](https://github.com/freedomofpress/dangerzone/actions/runs/8335345371/job/22810663840#logs)), `build-image.py` now fails during the "Preparing metadata" step,
in particular there are errors (e.g., `'FzStextPage' does not name a type; did you mean 'fz_stext_page'?`)
when compiling `libmupdfcpp.so`.

**Comment by apyrgio** [comment]
Thanks for pointing out these errors. I hoped they would be transient, but they still persist. Also, I can reproduce them in a vanilla Alpine Linux container.

Since we have not changed something in the way we build our container images in the past few days, I opened an issue in PyMuPDF's bug tracker: https://github.com/pymupdf/PyMuPDF/issues/3279
