### ISSUE TITLE
Package for Opensuse Tumbleweed

### ISSUE THREAD

**Issue by bmp** [freedomofpress/dangerzone#809]
Thank you for the wonderful tool, is there any possibility of a package for Opensuse Tumbleweed?

**Comment by apyrgio** [comment]
Thanks for the kind words Barath, as well as your suggestion. Yes, we definitely want to have support for more distros in the future. The most reasonable path forward though looks like through Flatpak: https://github.com/freedomofpress/dangerzone/issues/45. It's a feature that has been discussed for quite some time, but due to some extra complexity and lack of traction, it hasn't materialized yet.

In the meantime, you can always run Dangerzone [from source](https://github.com/freedomofpress/dangerzone/blob/main/BUILD.md). I do understand that it's a subpar solution, but just making sure you are aware of the alternatives.

Closing this issue for now, but feel free to discuss more either here, on in the respective Flatpak issue.
