### ISSUE TITLE
File is too large?

### ISSUE THREAD

**Issue by emadockerzone** [freedomofpress/dangerzone#917]
When trying to convert my Pdf it stops and says "A page exceeded the maximum height". Please can somene explain to me if it has to do with the size of the Pdf, the size of the pages, or anything else. I need this for work and it would be wonderful if it worked. Thanks

**Comment by apyrgio** [comment]
Hi @emadockerzone, thanks for the bug report. Let's dig into it and find out some things first:

1. What is your Operating System?
2. What is your Dangerzone version?
3. Does the original PDF contain any special elements?
    * If you believe it's malicious, no need to open it, skip this question.
4. Do other PDF files fail similarly?

As for the error message, it means that the page height may exceed 10,000 pixels. This would be a **very** unusual PDF though.

Instead, what is more probable, is that you're hitting a known bug in the latest versions, where Dangerzone fails with this error message if there are multimedia elements (audio/video) in the PDF. We have already fixed this bug, but the next release that will contain the fix may take a while (we're shooting for mid-October).

**Comment by emadockerzone** [comment]
Hi, of course
1. Windows 64bit12th generation with Windows 11
2. My dangerzone says Dangerzone 0.7.0 idk if it is the latest version though(?
3. Yes it does, It actually is a interactive pdf with buttons to go from some pages to another ones but it usually works fine, now, it says that it may cause damage to my device but I dont know why... 
4. I just run another one (also with interactive buttons) that doesnt have that problem and it does work. 
I will be waiting for your answer, thank you very much :)

**Comment by apyrgio** [comment]
I see. It's quite possible that the fix I mentioned will help, given that there are some non-standard elements in the PDF, but unfortunately we don't have nightly builds that you can test. The only other option is building Dangerzone from source, if that's something you're familiar with.

> now, it says that it may cause damage to my device but I dont know why...

Dang, that's not nice. That's probably a message that your PDF reader throws whenever there's a risky element in a PDF. I have a few suggestions here:
1. If you have a designated IT person at work, ask them to take a look. Maybe they can produce another clean copy for you.
2. If your document **is not sensitive**, and you upload it to a cloud service (e.g., Google Drive), then you can view it safely there. Again, this works only for non-sensitive documents.
3. **Strictly for harm reduction purposes**, I think the last Dangerzone version that doesn't have this bug is [0.5.1](https://github.com/freedomofpress/dangerzone/releases/tag/v0.5.1). You can download the .msi file from that page and install it. If it renders your document, then please remember to reinstall the latest Dangerzone version.

**Comment by apyrgio** [comment]
Hi @emadockerzone. Just so you know, this issue has closed because we expect that the upcoming 0.8.0 Dangerzone release will solve it. We have also added a test case so that we don't have a regression in the future. Thanks for the report, let us know if the new release helps, once it's out. If not, feel free to reopen this issue.
