### ISSUE TITLE
Fedora 41 RPM

### ISSUE THREAD

**Issue by boredsquirrel** [freedomofpress/dangerzone#947]
Fedora 41 just came out, an RPM in the repo would be great.

If there is a place where the spec file lies, I could try to do it

**Comment by apyrgio** [comment]
Whoops, thanks a lot for the heads up! Yeah, we need to get out an RPM soon, and we'll work on that right now. Actually, we just realized a few things, prompted from this issue:
1. Ubuntu 24.10 is also out since October 10th! We need a Debian package for that as well.
2. Fedora 41 will _actually_ be released on October 22nd: https://fedorapeople.org/groups/schedule/f-41/f-41-key-tasks.html
3. In our release instructions, we mention that we check for **new** releases, and for **EOL** releases, but not for beta/RC releases. We plan to start supporting those from 0.8.0 onwards.

**Comment by apyrgio** [comment]
Heads up: We've merged support in our `main` branch, and we'll start building packages soon. I'll update the issue once we have packages for Fedora 41 and Ubuntu 24.10 out.

**Comment by apyrgio** [comment]
We now have packages out for Ubuntu 24.10 and Fedora 41. Let us know if you run into any issues.
